const emails = [
    "wissal.doumi@cbi.ma",
    "itsolutions@intelcia.com",
    "contact@radiumdigital.ma",
    "contact@digitalandcreativity.com",
    "contact@digitalholding.ma",
    "contact@digitalclub.ma",
    "Contact@digitalma.ma",
    "contact@digitalad.ma",
    "contact@up-skill.org",
    "contact@pixelweb.ma",
    "contact@softas.ma",
    "contact@apexagency.ma",
    "contact@softydev.com",
    "contact@infomed-tech.com",
    "simo.asmouh@gmail.com",
    "mazouari@powerm.ma",
    "contact@creation-site-maroc.ma",
    "contact@inovteam.com",
    "contact@highsystemsinfo.com",
    "Contact@jokesigner.com",
    "khadija.marine@sofrecom.com",
    "webagency.maroc.group@gmail.com",
    "cbi@cbi.ma",
    "talentunit.ma@capgemini.com",
    "Imane.machane@hps-worldwide.com",
    "Contact@adria-bt.com",
    "contact@finatech.com",
    "cv@dba.ma",
    "hello@dba.ma",
    "contact@cbo.ma",
    "cvjob1.ma@gmail.com",
    "contact@mediadigitalinvest.com",
    "k.bouhfid@bhfsoft.com",
    "bonjour@inventiv-it.fr",
    "hello@wht.agency",
    "manal.mbarki@capgemini.com",
    "fchaffai@xperlean.com",
    "contact@digispaceagency.net",
    "application.cofma@coficab.com",
    "recrutement@valinnov.tech",
    "oriigami.contact@gmail.com",
    "scoopevent0@gmail.com",
    "g_kouehion@yahoo.com",
    "hiba.falky@marketingconfort.com",
    "soukaïna.akhd@bi-newvision.com",
    "Oumaima.Mahboub.STG@teal.ma",
    "chaimaa.anaddam@bertrandt.com",
    "job.maroc@inetum.com",
    "recrutement.yvesrochermaroc@yrnet.com",
    "administration@auditec.ma",
    "wiam.el-baamrani@airbus.com",
    "eya.youssfi@digixer.fr",
    "chokrane.belhaj@digixer.fr",
    "recrutement@digispaceagency.net",
    "nadasalki38@gmail.com",
    "afrimet.marocc@gmail.com",
    "m.recrutement2018@gmail.com",
    "recrutement@masterlab.ma",
    "rhrecrutement180@gmail.com",
    "candidature@axa-services.ma",
    "myjob@timlogsolutions.com",
    "z.tawfiki@eolcenter.net",
    "team@tidar.ma",
    "hafsa.badry@alpha55.ma",
    "recrutement@agma.co.ma",
    "fatima-ez-zahra.fadili@atos.net",
    "raihanabelmadani@prestafreedomprod.com",
    "stages@caf-technologies.com",
    "bouykarouane.abdelali@gmail.com",
    "i.obayd@black-box.ma",
    "hamzaamgouj054@gmail.com",
    "everestosagency@gmail.com",
    "najwa.mirani@skylark.ma",
    "chaimae.zarkani@deltalink.ma",
    "recrutement@superauto.ma",
    "amal.lasri@niji.fr",
    "contact@rubicon.ma",
    "khaoula.taha@skylark.ma",
    "aymane.ramou.2017@gmail.com",
    "hajar.workwide@gmail.com",
    "recrutement@mabelka.com",
    "careers@argoteamgroup.com",
    "kawtar.boulkaid@lemonderh.ma",
    "Ahmed.benbrahim@bi-newvision.com",
    "jihane.bennani@sabiss.net",
    "n.cherkaoui.sellami@accenture.com",
    "khaoula.touri@rs-telecom.fr",
    "nouhaila.brija@sofrecom.com",
    "ons.louhichi@ezeegenai.dev",
    "samhidi@gear9.ma",
    "application.cofkt@coficab.com",
    "recrutement@vnb-it.fr",
    "OffresdeEmploi24@gmail.com",
    "kenza.elboury@docaposte.fr",
    "n.labzour@mascir.ma",
    "Kenza.bakkar@alten.com",
    "contact@codingart.io",
    "rh-talent@g3c.ma",
    "oussama.ezzaytouni@africashore.com",
    "rh@mail.digi4.ma",
    "example@mail.com",
    "compliance@jooble.com",
    "privacy@jooble.com",
    "ihelp@idigitalise.net",
    "jane.doe@acme.com",
    "contact@technologies-4you.com",
    "oumaima.e@adex-personnel.com",
    "hibaamgbuilding@gmail.com",
    "recrutement@utopiha.fr",
    "rh@tthgroupe.com",
    "sara.nafi@walitservices.com",
    "amal.amegoude@akkodis.com",
    "abderrahimabbad25@gmail.com",
    "imad.hammane@welink.ma",
    "safaedriouach0@gmail.com",
    "miacorps.tanger@gmail.com",
    "isardari41@gmail.com",
    "h.hamdi@tro.ma",
    "recrutementkicklox@gmail.com",
    "gastrorecrut14@gmail.com",
    "rh@sn-investment.ma",
    "agencetanger@manpower-maroc.com",
    "rh@aep.ma",
    "recrutement.dynamictalentsearch@gmail.com",
    "cv@marwa.com",
    "kenitra.carriere@sews-e.com",
    "hse.newgeneration@gmail.com",
    "chaimae.elhaloui@sully-group.com",
    "mariammakboul98@gmail.com",
    "impactskills03@gmail.com",
    "kawthar.bennani@niji.fr",
    "nabil.sbaghi@dekra.com",
    "neko.tech.ma@gmail.com",
    "contact@hr-development.fr",
    "centralerh901@gmail.com",
    "recrutement@artizal.ma",
    "oumaima.c@consultingdatamed.com",
    "mehdi@sygma.ai",
    "1@socgen.com",
    "20@akwagroup.com",
    "6@gmail.com",
    "a.balqui@brosahel.com",
    "a.benghalem@akwagroup.com",
    "a.chaibi@akwagroup.com",
    "a.chergui@aluminiumdumaroc.com",
    "a.elamrani@smesi.com",
    "a.elbardi@outlook.com",
    "a.elmouhili@gmail.com",
    "a.ennoni@akwagroup.com",
    "a.ennouni@akwagroup.com",
    "a.fatmi@mu-b-solution.com",
    "a.ghoulam@gfimaroc.com",
    "a.hentour@akwagroup.com",
    "a.kannour@maroc-bakertilly.com",
    "a.kaoutar@athena-surveillance.com",
    "a.karame@dafmaroc.com",
    "a.mesbahi@arbagri.com",
    "a.neifi@akwagroup.com",
    "a.nourelhadi@inflexit.com",
    "a.sekkak@shell.com",
    "a.semrich@polytechnet.com",
    "a.souad@akwagroup.com",
    "a.zaghloun@akwagroup.com",
    "a2zevent.contact@gmail.com",
    "aagzenai@lear.com",
    "aak@charaf.com",
    "ismailibeton@gmail.com",
    "aalami@cam-industries.com",
    "aalascam@hotmail.com",
    "aamejrar@imalum.com",
    "aatafay-med@hotmail.com",
    "abagmo@abagdev.com",
    "abdallah.achmaoui@beiersdorf.com",
    "abdel.azza@gmail.com",
    "abdelali.qualite@gmail.com",
    "abdelali.tahri@africa.bnpparibas.com",
    "abdelaziz.khalkhal@st.com",
    "abdelbasset.essoufi@gmail.com",
    "abdelfattah.filali@brusselsairlines.com",
    "abdelfettah.beliamime@cegelec.com",
    "abdellah.agouzoul@sews-e.com",
    "abdellah.malek@starchim.com",
    "abdellah.sabri@cegelec.com",
    "abdellah.sanhaji@cegelec.com",
    "abdellatif.hamdaoui@cegelec.com",
    "abderrahim.taoussi@coats.com",
    "abderrahman.bouad@sews-e.com",
    "abennouna@royalairmaroc.com",
    "abmeca@mtds.com",
    "aboubi@onhym.com",
    "abouyaala.khaoula@awb.com",
    "acas@cam-industries.com",
    "acecar.ma@gmail.com",
    "achaima.benba@sgcib.com",
    "achmarkh@atretis.com",
    "achrafal@hotmail.com",
    "acier@serima-maroc.com",
    "ad.idrissi@gmail.com",
    "adakir@jnjma.jnj.com",
    "adamagro1@gmail.com",
    "adel.rbii@pfizer.com",
    "adm@norafood.com",
    "admaroc@autodistribution.com",
    "admcontact@aluminiumdumaroc.com",
    "admin.rh@michlifen.com",
    "admin@energytransfo.com",
    "aechcherki@ma.ibm.com",
    "aelguir@mmm.com",
    "africphar@africphar.com",
    "afrique_optical@hotmail.com",
    "agdmng@maersk.com",
    "aghbalou1972@hotmail.com",
    "aghmiri007@hotmail.com",
    "agora@hotmail.com",
    "agourram-expert@hotmail.com",
    "aguitec.sarl@yahoo.com",
    "ahettani@centralelaitiere.com",
    "ahlam.bakkal@unilever.com",
    "ahmed.azmi@dhl.com",
    "ahmed.bastani@inetum.com",
    "ahmed.wagih@loreal.com",
    "ahmedneggaoui@caramail.com",
    "aicha.boussagui@cgi.com",
    "aicha.boussagui@eurafric-information.com",
    "aicha@aicha.com",
    "aisoard@cfao.com",
    "akalayrabia@gmail.com",
    "akhaih@fycomputing.com",
    "alahmadiya@hotmail.com",
    "alamelec.ma@gmail.com",
    "alaoui.ismaili.g1@gmail.com",
    "alefsa@alefsa.com",
    "alexandra.roux@loreal.com",
    "alhachimi@sqli.com",
    "alina_li@huawei.com",
    "alinou@gmail.com",
    "allal.bouchannafa@movenpick.com",
    "aludin1@yahoo.com",
    "amal.bouazzi@clariant.com",
    "amaroc-sif@amaroc-sif.com",
    "amin.melloul@inetum.com",
    "amina.berrada@akwagroup.com",
    "amina.gharib@fiat.com",
    "amina.lahkim@ma.dti.bollore.com",
    "amina.massaoudi@faurecia.com",
    "amina.rouane@csplc.com",
    "amine.bennani@jesagroup.com",
    "amine.oulahyane@ma.atlascopco.com",
    "amine@neurones.com",
    "amountassir@maroctelecommerce.com",
    "amourdesrose@hotmail.com",
    "anas.naja@dxc.com",
    "andreea_lupu@cargill.com",
    "ane@caramail.com",
    "ankacorp@ankacorp.com",
    "anthony.drugeot@faurecia.com",
    "aouguerzi@gmail.com",
    "arafiq@groupe-bel.com",
    "arahmane@airarabia.com",
    "arcadtechnologie@caomecaservice.com",
    "aridachafi@kohlereurope.com",
    "arouyer@email.rmo-maroc.com",
    "art@the-art-company.com",
    "asamri@somepigroup.com",
    "aslaoui@stokvis-maroc.com",
    "asmaa.chiguer@sofrecom.com",
    "asmaa.el-bouhali@capgemini.com",
    "asmaa.elbouhali@capgemini.com",
    "asmaa.marzaoui@gonvarri.com",
    "asmaa.tazi@marocconnect.com",
    "asmae.elfaghloumi@gmail.com",
    "asmae.hedidane@sews-e.com",
    "asmakmorsad@hotmail.com",
    "asmamamaroc@asmamamaroc.com",
    "ass-industrie@ass-industrie.com",
    "assid.houbane@gmail.com",
    "assila@hotmail.com",
    "assistanterecrutement01@gmail.com",
    "assistecrh@gmail.com",
    "assya.hilal@matis-aero.com",
    "atif.taoufik.sosconstat@gmail.com",
    "atlantic@mtds.com",
    "atlascopco.maroc@atlascopco.com",
    "avale@aubay.com",
    "avelsch@ma.loreal.com",
    "avenir@mtds.com",
    "aya.hassib@berexia.com",
    "ayoub.ansair@solway-cs.com",
    "ayoub.dinary@cgi.com",
    "ayoub.tangershoes@gmail.com",
    "azbane@laboratoires-azbane.com",
    "azid.mougari@beiersdorf.com",
    "aziz.elhayani@hilton.com",
    "aziz.mestassi@sicome.com",
    "faissal@fadesa.es",
    "hfa.marruecos@ral.es",
    "imccelis@torraspapel.es",
    "maroc@indas.es",
    "nourdine@covercar.es",
    "sefrimarruecos@terra.es",
    "settat@piman.es",
    "vega@luma.es",
    "yfismael@bmb.es",
    "1@voila.fr",
    "a.arsala@hotmail.fr",
    "aabaselhassane@yahoo.fr",
    "abcconso@hotmail.fr",
    "abenajiba@fromageries-bel.fr",
    "afra_mas@yahoo.fr",
    "africdigital@yahoo.fr",
    "albouchra05@yahoo.fr",
    "alfajrconsulting@yahoo.fr",
    "aliapneu@yahoo.fr",
    "alielmadkoury@yahoo.fr",
    "amaury.callens@t2o.fr",
    "amezianeahmed18@yahoo.fr",
    "amine.chami@teuchos.fr",
    "anouar71@yahoo.fr",
    "areaconsul@wanadoo.fr",
    "arnaud.girard@atab.fr",
    "assistante3@yahoo.fr",
    "atall@asi.fr",
    "atch@ahg.fr",
    "autexconsulting@yahoo.fr",
    "auto4ricard@yahoo.fr",
    "axomar@hotmail.fr",
    "b.beaudouin@my-kiwi.fr",
    "barelec_74@hotmail.fr",
    "basma.ghafir@yahoo.fr",
    "bbeniluz@ciea.fr",
    "bbimaroc@yahoo.fr",
    "bekkali.hamza@hotmail.fr",
    "benamerabdelkrim@yahoo.fr",
    "bendatiss02@yahoo.fr",
    "benkiranbadr@yahoo.fr",
    "biopharma_ma@yahoo.fr",
    "bmz@enginov.fr",
    "broyardjerome@hotmail.fr",
    "btissam.bergannou@econocom.fr",
    "c.gallos@logware.fr",
    "caouraghe@deloitte.fr",
    "cderaoui@deloitte.fr",
    "cerimme@yahoo.fr",
    "cetelec-maroc@cetelec.fr",
    "charaf@hotmail.fr",
    "chaussuma@yahoo.fr",
    "chmireq@yahoo.fr",
    "christian.carbone@orange.fr",
    "cibleverte@hotmail.fr",
    "cmrb@hotmail.fr",
    "cokabelec@yahoo.fr",
    "cometalauxsnc@yahoo.fr",
    "contact@ciea.fr",
    "contact@studassist.fr",
    "cpcmrh@yahoo.fr",
    "creuzet@creuzet.fr",
    "damous1965@yahoo.fr",
    "daniel.chazelle@wanadoo.fr",
    "davina.purdessy@acensi.fr",
    "dcrb.oujda@yahoo.fr",
    "dimac@cfao.fr",
    "dlcindustrie@yahoo.fr",
    "drh@exmc.fr",
    "drh@ratier-figeac.fr",
    "drhofppt@yahoo.fr",
    "e.chavry@hays.fr",
    "ecrut.ma@alteis.fr",
    "ejouf@yahoo.fr",
    "emploi-rfm@ratier-figeac.fr",
    "erriyachi@yahoo.fr",
    "f.d.i@hotmail.fr",
    "fabcanale@yahoo.fr",
    "fakirnaima2005@yahoo.fr",
    "futuraplast2000@yahoo.fr",
    "g.coupe@alltech.fr",
    "georges.le-cam@wanadoo.fr",
    "graindorge5@wanadoo.fr",
    "habbarinadia@yahoo.fr",
    "hallaouihala@yahoo.fr",
    "hasadok@airfrance.fr",
    "hassane_moum@yahoo.fr",
    "hhassouni@deloitte.fr",
    "houazi@deloitte.fr",
    "hraouia_amal@yahoo.fr",
    "ibrahim.elamrani@creditlyonnais.fr",
    "ijouini@lyndatas.fr",
    "integrateur@demos.fr",
    "intermotors@cfao.fr",
    "jean-claude.baratte@treves.fr",
    "jean.claude.dion@wanadoo.fr",
    "jobs@neosys.fr",
    "kafhayainesad@yahoo.fr",
    "kchakir@deloitte.fr",
    "kinebennani@hotmail.fr",
    "l.scardigno@hays.fr",
    "lecnja1991@hotmail.fr",
    "line.energy@yahoo.fr",
    "live_your-life@hotmail.fr",
    "lletteron@egide.fr",
    "lprunet@sigmapole.fr",
    "m-mahloub@hotmail.fr",
    "mahanni.fatima@yahoo.fr",
    "manorbois@cfao.fr",
    "maroc@reso.fr",
    "mbeghiel@tronico.fr",
    "mbounnaceur@magic.fr",
    "med.sajid@yahoo.fr",
    "mfaugra@free.fr",
    "mhakmy@deloitte.fr",
    "mhsaini@deloitte.fr",
    "mohamed.gandoura@adservio.fr",
    "mrghioui@jacobdelafon.fr",
    "mustaphahamdani@hotmail.fr",
    "mvrevolution@magic.fr",
    "n_jahri@yahoo.fr",
    "nadorinvest@yahoo.fr",
    "naggar-samah@hotmail.fr",
    "najlaa.hachami@hotmail.fr",
    "narjisla@yahoo.fr",
    "nathaliegeschwind@yahoo.fr",
    "nboulmani@deloitte.fr",
    "palmeraie605@yahoo.fr",
    "parville@cegetec.com.fr",
    "pharma2006huberka@yahoo.fr",
    "prigros2003@yahoo.fr",
    "profeta.giovanni@tiscali.fr",
    "proff.recrutement@yahoo.fr",
    "progigest@live.fr",
    "provitel15@yahoo.fr",
    "qualiclim@yahoo.fr",
    "rabahi@airfrance.fr",
    "rajaa_zz@yahoo.fr",
    "recrutement.agadir@norsys.fr",
    "recrutement.hertz-maroc@gbh.fr",
    "recrutement5@yahoo.fr",
    "recrutement99@yahoo.fr",
    "recrutement9@yahoo.fr",
    "recrutement@oxyl.fr",
    "recrutement@percall.fr",
    "recrutementnaf@norsys.fr",
    "rh-ito@athic.fr",
    "rh.marocco.recrutement@alyotech.fr",
    "rh@btc-web.fr",
    "rharis@snop.fr",
    "s.genereux@hotmail.fr",
    "s_hlimi@hotmail.fr",
    "saei.afrilumiere@yahoo.fr",
    "safia@boa.fr",
    "sagmeiaghou@yahoo.fr",
    "salanova-philippe@yahoo.fr",
    "sandbellot@yahoo.fr",
    "sara.mahli@datalake.fr",
    "sarpdoil_maroc@yahoo.fr",
    "sebballet@yahoo.fr",
    "selmorabet@fram.fr",
    "siham1_ma@yahoo.fr",
    "sihambennane@yahoo.fr",
    "slim106d@hotmail.fr",
    "sofrench2005@yahoo.fr",
    "sogea-maroc@sma.sogea.fr",
    "somathes@yahoo.fr",
    "soufiane.68@live.fr",
    "ste_medaz@yahoo.fr",
    "taibitayeb50@yahoo.fr",
    "tbartex@yahoo.fr",
    "techma@wanadoo.fr",
    "thephsol77@yahoo.fr",
    "transparence_1@yahoo.fr",
    "tscindustrie@yahoo.fr",
    "tvcinter@yahoo.fr",
    "vrubio@msi-experts.fr",
    "wot@wanadoo.fr",
    "zalholding@yahoo.fr",
    "zekricopaph@yahoo.fr",
    "1@menara.ma",
    "2litfz@menara.ma",
    "3@menara.ma",
    "3c@trois-c.ma",
    "3plus@iam.net.ma",
    "4r@weldom.ma",
    "5mdoune@cosumar.co.ma",
    "6po@menara.ma",
    "a-azmi@odep.org.ma",
    "a-novomaroc@a-novo.ma",
    "a.abbou@labelvie.ma",
    "a.akrouma@dlm.ma",
    "a.benjelloun@alomrane.gov.ma",
    "a.benjfine@bkam.gov.ma",
    "a.benthami@aromes.ma",
    "a.bouallou@ost.co.ma",
    "a.direct@iam.net.ma",
    "a.dounia@open.net.ma",
    "a.elhaossasse@tangermed.ma",
    "a.elouarzazi@agma.co.ma",
    "a.essemlali@iam.ma",
    "a.hanouf@casablanca-technopark.ma",
    "a.hayat@cimeq.ma",
    "a.kettani@wanadoopro.ma",
    "a.m.b@wanadoo.net.ma",
    "a.m.c@menara.ma",
    "a.moustaader@labelvie.ma",
    "a.pharma@atlasnet.net.ma",
    "a.tifaf@avendis.ma",
    "a.zaghloun@akwagroup.ma",
    "a.ziyani@akdital.ma",
    "a@iam.net.ma",
    "a@wanadoopro.ma",
    "ab.bennani@atlasnet.net.ma",
    "ab.fr@menara.ma",
    "ab.groupe@casanet.net.ma",
    "ab.industrie@menara.ma",
    "ab.services@iam.net.ma",
    "abazaou@nabc.ma",
    "abctanger@iam.net.ma",
    "abdelaali.rafik@inwi.ma",
    "abdelkebir.badalla@cnss.ma",
    "abdelkebirmoutawakkil@sce.co.ma",
    "abdellah.chenguiti@nexans.co.ma",
    "abdellatif.tazi@inwi.ma",
    "abdellatifi@cmr.gov.ma",
    "abdelmoumen.aghoulad@awsm.ma",
    "abdenbi.gharbi@betonchantier.ma",
    "abderrahim.allali@cyclad.ma",
    "abderrahim.elazhari@mawarid.co.ma",
    "abderrahim.elbasraoui@inwi.ma",
    "abderrahmane.tamsouri@alcatel.ma",
    "abdessamad.rakik@siemens.co.ma",
    "abenjelloun@alliances.co.ma",
    "abennani@compucom.co.ma",
    "abindustrie@menara.ma",
    "abkabbaj@softgroup.ma",
    "abourachdi@atlasnet.net.ma",
    "acc@open.net.ma",
    "access@acc.co.ma",
    "accessinterim@menara.ma",
    "accounts@jbmaroc.ma",
    "achibane@oncf.ma",
    "achoukir@intelcom.co.ma",
    "achro@marocnet.net.ma",
    "acjh@menara.ma",
    "acomasti@iam.net.ma",
    "acpelec@iam.net.ma",
    "acrelectroniq@acre.ma",
    "acrelectronique@acre.ma",
    "activar@iam.net.ma",
    "ad@somaca.co.ma",
    "adaddane@s2m.net.ma",
    "addoha@addoha.ma",
    "adhoc@menara.ma",
    "adi@adi.ma",
    "adillamrani@bestpro.co.ma",
    "adilnj@menara.ma",
    "adlim@wanadoo.net.ma",
    "adlitteram@adlitteram.ma",
    "adm.zine@holfipar.co.ma",
    "adm@mepnet.gov.ma",
    "admin@netas.ma",
    "administrateur@prestige.net.ma",
    "administration@odep.org.ma",
    "adnane.zarrari@pgp.ma",
    "adricom@iam.net.ma",
    "adritec@menara.ma",
    "adritecmaroc@menara.ma",
    "adsmaroc@menara.ma",
    "advanced@wanadoo.net.ma",
    "aebadissi@bmcebank.co.ma",
    "aelhouari@marocleasing.ma",
    "aema@iam.net.ma",
    "aeronautique_sefcam@menara.ma",
    "aessemlali@cgi.ma",
    "afaik@marocleasing.ma",
    "afc@winner.net.ma",
    "afcain@mail.sif.net.ma",
    "afcoal@mail.sis.net.ma",
    "afethi@ctth.ma",
    "afit.ca@iam.net.ma",
    "afl@casanet.net.ma",
    "aflac@menara.ma",
    "aflalo@navimar.ma",
    "afric-transfo@menara.ma",
    "afric@menara.ma",
    "afric_industries@maminet.net.ma",
    "africamaroc@marocnet.net.ma",
    "africamaroc@menara.ma",
    "africmesure@iam.net.ma",
    "africode@casanet.net.ma",
    "africode@menara.ma",
    "afrimo@iam.net.ma",
    "afs@maghrebnet.net.ma",
    "afskirat@menara.ma",
    "aga.ing@facenet.net.ma",
    "aga@wanadoopro.ma",
    "ages@wanadoo.net.ma",
    "aghazzali@acaciamarit.ma",
    "agroc@iam.net.ma",
    "agrofood@iam.net.ma",
    "agvimar@iam.net.ma",
    "agz@wanadoo.net.ma",
    "ahmal@iam.net.ma",
    "ai@menara.ma",
    "aicm@menara.ma",
    "aidassur@wanadoopro.ma",
    "aiguebelle@aiguebelle.co.ma",
    "aini.badr@orange.ma",
    "ainsimaroc@menara.ma",
    "airclima@wanadoopro.ma",
    "airindus@iam.net.ma",
    "ajmarou@nabci.ma",
    "akbibou@marjane.ma",
    "akhettab@casanet.net.ma",
    "alachkar@atento.ma",
    "alami@orca.ma",
    "alamitec@menara.ma",
    "alchem@casanet.net.ma",
    "alco@casanet.net.ma",
    "alezeraa@iam.net.ma",
    "alfarabi@casanet.net.ma",
    "alhalabi@wanadoo.net.ma",
    "ali61@menara.ma",
    "alia.pneu@iam.net.ma",
    "alifmetal@iam.net.ma",
    "aliose@menara.ma",
    "allam-dwarf@menara.ma",
    "alliances@techno.net.ma",
    "allplast@iam.net.ma",
    "almanar.sa@almanar.ma",
    "almanar@iam.net.ma",
    "alomdunord@iam.net.ma",
    "alouatmohamed@orange.ma",
    "alpha.bureau@iam.net.ma",
    "alphacsd@alpha.net.ma",
    "alphausine@menara.ma",
    "alstom.maroc@wanadoopro.ma",
    "alumteu@iam.net.ma",
    "alyousrrh@alyousr.ma",
    "amal.zoheiri@lydec.co.ma",
    "amal@maghrebsteel.ma",
    "amanor@menara.ma",
    "amazini@autofiller.ma",
    "amimi@lesieur-cristal.co.ma",
    "amina.berrada@akwagroup.ma",
    "amina.zegani@marsamaroc.co.ma",
    "amine.belkeziz@upline.co.ma",
    "amip@iam.net.ma",
    "amistad@iam.net.ma",
    "amitech-maroc@menara.ma",
    "amosig@menara.ma",
    "amp-ge@menara.ma",
    "amp@wanadoo.net.ma",
    "amti@casanet.net.ma",
    "amti@menara.ma",
    "anacleto@matel.co.ma",
    "anas.elalaoui@activeo.ma",
    "andre.robelin@interfer.ma",
    "andre.robelin@marocnet.net.ma",
    "anibar@colorado.ma",
    "anoirelmanar@menara.ma",
    "anpme@anpme.ma",
    "antoine.vosluisant@snecma.ma",
    "apr@casanet.net.ma",
    "apr@menara.ma",
    "arca@menara.ma",
    "arca@menara.net.ma",
    "arcenciel.tce@menara.ma",
    "arcobeton@wanadoo.net.ma",
    "arcol@marocnet.net.ma",
    "are.snec@iam.net.ma",
    "arica-international@iam.net.ma",
    "arin@menara.ma",
    "armor.ind@casanet.net.ma",
    "arnauld@menara.ma",
    "aroc@iam.net.ma",
    "arreda@iam.net.ma",
    "as-chim@casanet.net.ma",
    "as.maroc@wanadoo.net.ma",
    "asm@altairsecurite.ma",
    "asmetal.sa@casanet.net.ma",
    "asminaglaces@menara.ma",
    "asomie@menara.ma",
    "assia@egida.ma",
    "assidom@menara.ma",
    "assistec@iam.net.ma",
    "assmama@menara.ma",
    "ast@menara.ma",
    "asta@asta.co.ma",
    "at-work@atlasnet.net.ma",
    "at@wanadoo.net.ma",
    "atajeddine@savola.ma",
    "ataleb@orange.ma",
    "atcm@casanet.net.ma",
    "atdan@atlasnet.net.ma",
    "atecnicom@wanadoo.net.ma",
    "ateico@wanadoo.net.ma",
    "atel.am@menara.ma",
    "atlas-stone@menara.ma",
    "atlas.v.i@wanadoopro.ma",
    "atlasassistance@menara.ma",
    "atlasbatiment@wanadoo.net.ma",
    "atlaship@iam.net.ma",
    "atlasinfo@atlasnet.net.ma",
    "atlasmat@iam.net.ma",
    "atlastou@iam.net.ma",
    "attaghlif@wanadoo.net.ma",
    "auditas@auditas.ma",
    "augier@stam.ma",
    "autelec@autelec.ma",
    "auterep@menara.ma",
    "auterepsarl@menara.ma",
    "auto-filler@iam.net.ma",
    "auto@menara.ma",
    "autohall@autohall.ma",
    "automatisme@menara.ma",
    "automove@iam.net.ma",
    "aval@menara.ma",
    "avantages@marocnet.net.ma",
    "avendis@avendis.ma",
    "avimar@avimar.ma",
    "avisaga@iam.net.ma",
    "ayoussfi@cdgcapital.ma",
    "azarbani@bcv.ma",
    "azarrouki@trarem.ma",
    "azbane@open.net.ma",
    "azbanedaf@wanadoopro.ma",
    "azit@menara.ma",
    "b.amina@akwagroup.ma",
    "b.benmessoud@inaam.ma",
    "b.buisson@wanadoo.net.ma",
    "b.e.t.e.c@menara.ma",
    "b.elidrissi@sbbc.co.ma",
    "b.redouane@akwagroup.ma",
    "ba@iam.net.ma",
    "bachaoui@oncf.ma",
    "back-office@adcapital.ma",
    "badiaa.melikh@matelpcmarket.ma",
    "badich@alhoceimainvest.ma",
    "badr@wanadoo.net.ma",
    "bahia.haddou@polymedic.ma",
    "bali@trarem.ma",
    "ballet@marocnet.net.ma",
    "ballet@wanadoopro.ma",
    "batifer@marocnet.net.ma",
    "batiform@wanadoo.net.ma",
    "battah@oncf.ma",
    "bavaria@wanadoopro.ma",
    "bchadia@mail.cbi.net.ma",
    "bcn@bcn.ma",
    "bds@iam.net.ma",
    "becomar@menara.ma",
    "bejnaoui@comana.co.ma",
    "bejnaoui@comanav.co.ma",
    "bekelec@iam.net.ma",
    "belkhayat@diagonale.ma",
    "belkora@cgi.ma",
    "bellaoui@colas-drm.co.ma",
    "bellesimpressions@wanadoopro.ma",
    "belltelecom@iam.net.ma",
    "belrhiti@rcar.ma",
    "ben.hadj@casanet.net.ma",
    "benbrahim@iam.ma",
    "benchekroun@domaines.co.ma",
    "benchelha@iam.net.ma",
    "bendaoud@menara.ma",
    "benfares@iam.net.ma",
    "benhammou@cbi.ma",
    "benhammou@mail.cbi.net.ma",
    "benident@iam.net.ma",
    "benjell1@mail.cbi.net.ma",
    "benkhadra@brpm.org.ma",
    "benmadani@obelectronique.ma",
    "bensaids@lamarocainevie.co.ma",
    "bensaltana@armconsultants.ma",
    "bentabet@one.org.ma",
    "benzerouk@latco.co.ma",
    "berenger@menara.ma",
    "beric@iam.net.ma",
    "bernard.prince@sofrecom.net.ma",
    "bernossi@msbernossi.ma",
    "bet@techniprojet.ma",
    "beting@iam.net.ma",
    "betra@iam.net.ma",
    "bilconsulting@marocnet.net.ma",
    "bio@techno.net.ma",
    "biocorp@iam.net.ma",
    "biomer@wanadoo.net.ma",
    "biotal@casanet.net.ma",
    "bipack@menara.ma",
    "biscaf@casanet.net.ma",
    "bjalil@trarem.ma",
    "blaabi@atlas-catering.ma",
    "blaftimi@phone-assistance.co.ma",
    "blocotelhamaroc@blocotelha.ma",
    "bmedirection@menara.ma",
    "bmfpmaroc@menara.ma",
    "bnmppp@techno.net.ma",
    "bottu@marocnet.net.ma",
    "bouchaib.nassef@oilibya.ma",
    "boukhabrine@menara.ma",
    "boumahdi@poste.ma",
    "bourachdi@menara.ma",
    "brahim.berrada@hps.ma",
    "brouz.adil@agrimatco.ma",
    "bsamir@trarem.ma",
    "buhler@iam.net.ma",
    "burintel@wanadoo.net.ma",
    "burog@burog.co.ma",
    "buroni@wanadoo.net.ma",
    "buzzichelli@iam.net.ma",
    "bwmaroc@iam.net.ma",
    "bymaro@cyber.net.ma",
    "c.elmeghraoui@alomrane.gov.ma",
    "c.h.k@c.h.k.ma",
    "c.i.a@wanadoo.net.ma",
    "c.m.h@iam.net.ma",
    "c.picard@aims.ma",
    "cabmaroc@iam.net.ma",
    "cac.compta@wanadoopro.ma",
    "cadaicassur@iam.net.ma",
    "cadilhac@iam.net.ma",
    "caet@iam.net.ma",
    "caf@fusion.net.ma",
    "cagemmaroc@cimr.ma",
    "caidelec@iam.net.ma",
    "calimaroc@menara.ma",
    "camai@casanet.net.ma",
    "camaral@wanadoo.net.ma",
    "camrani@jlec.co.ma",
    "candidat@deloitte.co.ma",
    "candidature.rh@s2m.net.ma",
    "candidature@novec.ma",
    "candidatures@cirestechnologie.ma",
    "cap2@digitalimage.ma",
    "cap@wanadoo.net.ma",
    "capelem@menara.ma",
    "capger@menara.ma",
    "capgibraltar@menara.ma",
    "capinter@iam.net.ma",
    "capram@iam.net.ma",
    "carbogaz@iam.net.ma",
    "carbonem@menara.ma",
    "careers@ocpgroup.ma",
    "careers@s2m.net.ma",
    "carmed@iam.net.ma",
    "carnaudmaroc@carnaud.co.ma",
    "carsud.casa@casanet.net.ma",
    "casafroid@iam.net.ma",
    "casamazout1@menara.ma",
    "casames@menara.ma",
    "casatherm@iam.net.ma",
    "catlim@menara.ma",
    "cbgn@iam.net.ma",
    "cbgsud@iam.net.ma",
    "cbm@iam.net.ma",
    "ccc@cccsunbeach.ma",
    "ccg@ccg.ma",
    "ccic@marocnet.net.ma",
    "ccism@iam.net.ma",
    "cct@mail.cbi.net.ma",
    "cdg@cdg.ma",
    "cdrif@iam.net.ma",
    "ceac@iam.net.ma",
    "cec@iam.net.ma",
    "ced-tanger@menara.ma",
    "celdis@wanadoopro.ma",
    "cellulose@maghrebnet.net.ma",
    "cellulose@magrebnet.net.ma",
    "cenelec@cenelec.co.ma",
    "centec@casanet.net.ma",
    "centralediesel@menara.ma",
    "centralparts@menara.ma",
    "centrelec@centrelec.ma",
    "cerabat@iam.net.ma",
    "ceratube@menara.ma",
    "cernam@smara.net.ma",
    "cetemco@iam.net.ma",
    "cetemo@menara.ma",
    "cetracasa@iam.net.ma",
    "cfd@menara.ma",
    "cfields@menara.ma",
    "cfiindustrielles@menara.ma",
    "cfme@menara.ma",
    "cga@wanadoo.net.ma",
    "cgeab@iam.net.ma",
    "cgr@iam.net.ma",
    "ch@intelcom.co.ma",
    "chadia@iam.net.ma",
    "chahid.med@toufer.ma",
    "chakib.benazzouz@akzonobel.ma",
    "charcomem@iam.net.ma",
    "chatinel@iam.net.ma",
    "chavis@iam.net.ma",
    "checobat@wanadoo.net.ma",
    "chennaoui@cdg.ma",
    "chennouf@oncf.ma",
    "cherifienne-incendie@wanadoo.net.ma",
    "chim@iam.net.ma",
    "chimicolor@casanet.ma",
    "chimicolor@casanet.net.ma",
    "chimicom@iam.net.ma",
    "chimiepro@iam.net.ma",
    "chimilabo@iam.net.ma",
    "chimipro.1@menara.ma",
    "chraibi@akwagroup.ma",
    "chraibim@petrom.ma",
    "chromage@menara.ma",
    "cia@iam.net.ma",
    "cicmate@menara.ma",
    "cicofap@connectcom.net.ma",
    "cid@cid.co.ma",
    "cid@did.co.ma",
    "cidagadir@cid.co.ma",
    "ciea@ciea.ma",
    "cielec@cielec.ma",
    "cifcasa@cif.co.ma",
    "ciftanger@cif.co.ma",
    "cim.ep@iam.net.ma",
    "cimel@menara.ma",
    "cimelect@atlasnet.net.ma",
    "cincib@casanet.net.ma",
    "cincib@menara.ca",
    "cinetele@wanadoopro.ma",
    "cipio.sa@iam.net.ma",
    "cipliindustrie@menara.ma",
    "cise@techno.net.ma",
    "cita@citabrior.ma",
    "citech.ing@atlasnet.net.ma",
    "cl@elan.net.ma",
    "cle@iam.net.ma",
    "client@elexpert.ma",
    "client@lavoieexpress.ma",
    "climair@iam.net.ma",
    "climate@wanadoo.net.ma",
    "climatric@iam.net.ma",
    "cm@menara.ma",
    "cmaef1@menara.ma",
    "cmaferi@iam.net.ma",
    "cmb@open.net.ma",
    "cmcm@techno.net.ma",
    "cmcp@iam.net.ma",
    "cmdalum@iam.net.ma",
    "cmh@open.net.ma",
    "cmm1@menara.ma",
    "cmpe@cmpe.org.ma",
    "cmpe@iam.net.ma",
    "cmpe@menara.ma",
    "cmpf@iam.net.ma",
    "cmr@cmr.gov.ma",
    "cnra@cnra.co.ma",
    "cnra@cnra.ma",
    "cobofin@iam.net.ma",
    "codexpro@wanadoo.net.ma",
    "coelma@iam.net.ma",
    "cofal@wanadoo.net.ma",
    "cofas@iam.net.ma",
    "cofasel@wanadoopro.ma",
    "coficab.kenitra@coficab.ma",
    "coflagamaroc@iam.net.ma",
    "cofremi@menara.ma",
    "cogepra@cogepra.ma",
    "cogetel1@iam.net.ma",
    "colainord@iam.net.ma",
    "colorado@colorado.ma",
    "comadel@iam.net.ma",
    "comafro@menara.ma",
    "comair@iam.net.ma",
    "comam@iam.net.ma",
    "comapiresa.rl@menara.ma",
    "comapra@iam.net.ma",
    "comaprom@iam.net.ma",
    "comaprom@menara.ma",
    "comaral@menara.ma",
    "comarbois@comarbois.ma",
    "comarev.sa@menara.ma",
    "comarev@iam.net.ma",
    "comatral@iam.net.ma",
    "comcris@iam.net.ma",
    "comega@menara.ma",
    "comelab@iam.net.ma",
    "comet@menara.ma",
    "cometalis@menara.ma",
    "comicom@wanadoo.net.ma",
    "commercial.pcs@tangermed.ma",
    "commercial@ingelec.ma",
    "commercial@smadia.co.ma",
    "commercial@trarem.ma",
    "communication@redal.co.ma",
    "comp.artopiel@menara.ma",
    "complipack@menara.ma",
    "compo@wanadoo.net.ma",
    "compta.alqantara@algest.ma",
    "compta2@recjac.co.ma",
    "comvesttanger@menara.ma",
    "concachi@menara.ma",
    "concept@wanadoo.net.ma",
    "conseil@convergenceconseil.co.ma",
    "consmar@iam.net.ma",
    "consult@menara.ma",
    "contact-clients@otis.co.ma",
    "contact.socodam@ssd.ma",
    "contact@adcapital.ma",
    "contact@ai-inside.ma",
    "contact@almada.ma",
    "contact@amee.ma",
    "contact@aquaelec.ma",
    "contact@asment.co.ma",
    "contact@batitherm.ma",
    "contact@bimo.co.ma",
    "contact@casablanca-precision.ma",
    "contact@cimat.ma",
    "contact@cmpe.ma",
    "contact@collabsys.ma",
    "contact@comicom.ma",
    "contact@cri-agadir.ma",
    "contact@dalton.ma",
    "contact@decisioconsulting.ma",
    "contact@ecowatt.ma",
    "contact@energyhandle.ma",
    "contact@energyvision.ma",
    "contact@gi3.ma",
    "contact@greenenergypark.ma",
    "contact@grocer.ma",
    "contact@groupeeuroloc.ma",
    "contact@heliantha.ma",
    "contact@ifmeree.ac.ma",
    "contact@innovation.ma",
    "contact@insoft.co.ma",
    "contact@intelcom.co.ma",
    "contact@inwi.ma",
    "contact@lm.co.ma",
    "contact@lydec.co.ma",
    "contact@maferi.ma",
    "contact@mekouarpartners.ma",
    "contact@neryou.ma",
    "contact@noops.ma",
    "contact@npsol.ma",
    "contact@ocpgroup.ma",
    "contact@precision.ma",
    "contact@promopharm.co.ma",
    "contact@sedec.ma",
    "contact@smcv.ma",
    "contact@smeteg.ma",
    "contact@solam.ma",
    "contact@solarpower.ma",
    "contact@tadlazilalinvest.ma",
    "contact@tandem.ma",
    "contact@tangermed.ma",
    "contact@thinksoft.ma",
    "contact@ugmi.ma",
    "contact@unimagec.ma",
    "contact@ynna.ma",
    "contactrecrutement@axa-services.ma",
    "contactsipps@menara.ma",
    "continen@iam.net.ma",
    "continental.s@alpha.net.ma",
    "controlunionmaroc@iam.net.ma",
    "coopermaroc@casanet.net.ma",
    "coopertec@menara.ma",
    "copag@iam.net.ma",
    "copayer@wanadoopro.ma",
    "cordoba@iam.net.ma",
    "coream@iam.net.ma",
    "corkout@iam.net.ma",
    "corsinaquatra@iam.net.ma",
    "cortec@menara.ma",
    "cota@iam.net.ma",
    "cotecna@iam.net.ma",
    "coupe@iam.net.ma",
    "courrier@nitam.ma",
    "couvermetal@menara.ma",
    "covem@iam.net.ma",
    "coveral@iam.net.ma",
    "cp.aero@menara.ma",
    "cpcm@atlasnet.net.ma",
    "cpcm@cpcm.ma",
    "cpit-pneu@iam.net.ma",
    "crb@wanadoo.net.ma",
    "cri@safi.ma",
    "cri@settatinvest.ma",
    "cridakhla@hotmail.ma",
    "crioujda@orientalinvest.ma",
    "crownmicro@menara.ma",
    "csb@cadtech.ma",
    "cseeh@menara.ma",
    "ctc.arca@menara.ma",
    "ctcm@iam.net.ma",
    "ctth@ctth.ma",
    "cv-positif-conseil@iam.net.ma",
    "cv.lms@menara.ma",
    "cv@agenz.ma",
    "cv@f2v.ma",
    "cv@iam.ma",
    "cv@inid.ma",
    "cv@positif-conseil.ma",
    "cwamaroc@iam.net.ma",
    "cwtdg@atlasnet.net.ma",
    "d.btprama@menara.ma",
    "d.esserghini@sothema.ma",
    "d.financiere@cimtex.ma",
    "d.parlanti@menara.ma",
    "dabenzit@iam.net.ma",
    "dahhan@menara.ma",
    "dama@atlasnet.net.ma",
    "dardar@alistitmaroo.ma",
    "dardis@dardis.ma",
    "darrabat@iam.net.ma",
    "datasupport@datasupport.ma",
    "datma@wanadoo.net.ma",
    "dco@menara.ma",
    "dd@ofppt.org.ma",
    "ddm@menara.ma",
    "deborel@deborel.ma",
    "dellant@iam.net.ma",
    "delta.1@iam.net.ma",
    "delta.pieces@iam.net.ma",
    "deltafish@menara.ma",
    "deltaindustrie@menara.ma",
    "deltamanagement@elan.net.ma",
    "deltasem@iam.net.ma",
    "deltherm@menara.ma",
    "demicron@atlasnet.net.ma",
    "demosa@iam.net.ma",
    "depastas@wanadoo.net.ma",
    "depjl@odep.org.ma",
    "detroit@wanadoo.net.ma",
    "deutalj@iam.net.ma",
    "dg.primarios@primarios.ma",
    "dg@deltaholding.co.ma",
    "dgcama@marocnet.net.ma",
    "dicapa@wanadoo.net.ma",
    "diemme_maroc@menara.ma",
    "dima@iam.net.ma",
    "dima@menara.ma",
    "dimameta@iam.net.ma",
    "dimateq@wanadoo.net.ma",
    "diorh@diorh.co.ma",
    "dircommerciale@maghrebsteel.ma",
    "direction@akdital.ma",
    "direction@bil.ma",
    "direction@cri-guelmim.ma",
    "direction@gtc.ma",
    "direction@laurentbouillet.ma",
    "dirpresse1@sochepress.ma",
    "dismatel@atlasnet.net.ma",
    "distralrabat@menara.ma",
    "distrib@ventec.ma",
    "districhimie@iam.net.ma",
    "diversam@iam.net.ma",
    "dmr@wanadoo.net.ma",
    "dnamaroc@menara.ma",
    "doc@anrt.net.ma",
    "dolidol@casanet.net.ma",
    "dounia.benkhraba@hilton.ma",
    "dounia.boustani@total.co.ma",
    "dounia.senhaji@alcatel.ma",
    "douniaplast@wanadoo.net.ma",
    "dr@wanadoo.net.ma",
    "dragados@open.net.ma",
    "drau.filtre@menara.ma",
    "draumet@menara.ma",
    "drh.info@wana.ma",
    "drh.mcco@menara.ma",
    "drh@atlasvoyages.co.ma",
    "drh@autohall.ma",
    "drh@cdg.ma",
    "drh@domaines.co.ma",
    "drh@ofppt.ma",
    "drh@petromin.ma",
    "drh@tractafric.co.ma",
    "drhnarevaholding@nareva.ma",
    "driss_ahardan@wanadoopro.ma",
    "drochal@maghrebnet.net.ma",
    "droplus@wanadoo.net.ma",
    "drorepar@wanadoo.net.ma",
    "dtastouri@pca.ma",
    "dvi@autohall.ma",
    "dzmaroc@marocnet.net.ma",
    "e-koutoubia@menara.ma",
    "e.farchakh@tmsa.ma",
    "e.gasperini@menaa.ma",
    "e@marocnet.net.ma",
    "e@wanadoo.net.ma",
    "eacce@eacce.org.ma",
    "eauglobe@iam.net.ma",
    "ebe.rabat@iam.net.ma",
    "ec2m@menara.ma",
    "eca@menara.ma",
    "ecai@menara.ma",
    "ech-isol@iam.net.ma",
    "echem@atlasnet.net.ma",
    "ecogulistan@iam.net.ma",
    "ecotherm@iam.net.ma",
    "ecowell@ecowell.ma",
    "efe.maroc@menara.ma",
    "eg6@menara.ma",
    "egape.industrie@menara.ma",
    "eie@wanadoo.net.ma",
    "eimb@iam.net.ma",
    "eiremor@iam.net.ma",
    "el@wanadoo.net.ma",
    "elataoui@wanadoo.net.ma",
    "elatiq@wanadoo.net.ma",
    "elbadri@colorado.ma",
    "elbaraka@wanadoo.net.ma",
    "elberindustrie@iam.net.ma",
    "elcotram@iam.net.ma",
    "elecaffo@elecaf.co.ma",
    "elecam@elecam.co.ma",
    "elecmar@elecmar.ma",
    "elecmar@iam.net.ma",
    "elecmar@marocnet.net.ma",
    "elecsys@menara.ma",
    "electramri@iam.net.ma",
    "electrimar@menara.ma",
    "electro.tafoghalt@iam.net.ma",
    "electrojac@menara.ma",
    "electronicszone@menara.ma",
    "eletec@eletec.ma",
    "elfanidi@iam.net.ma",
    "elfirdawsse.tazi@snecma.ma",
    "elfourat@iam.net.ma",
    "elg@casanet.net.ma",
    "elguirs@petrom.ma",
    "elhachimi.a@oncf.ma",
    "elhaimer.ahmed@sanad.ma",
    "elhakim1@iam.net.ma",
    "elhouari@mafoder.co.ma",
    "eliesrue@iam.net.ma",
    "elkarkouri@ntpnet.gov.ma",
    "ellamti@cmb-plastique.ma",
    "elouahidi@menara.ma",
    "elwehda@wanadoo.net.ma",
    "emagro@iam.net.ma",
    "emai@iam.net.ma",
    "ematrag@iam.net.ma",
    "embalcarton@iam.net.ma",
    "eme@marocnet.net.ma",
    "emploi@webdev.ma",
    "emra@iam.net.ma",
    "emrig@menara.ma",
    "emsa@casanet.net.ma",
    "emt@wanadoo.net.ma",
    "energet@menara.ma",
    "energieau@menara.ma",
    "energiessf@menara.ma",
    "ennaji@cmse.ma",
    "enretec@techno.net.ma",
    "envirotec@envirotec.ma",
    "eolane@menara.ma",
    "epcc@iam.net.ma",
    "epe@wanadoo.net.ma",
    "er@marocnet.net.ma",
    "er@open.net.ma",
    "erac - s@mhu.gov.ma",
  "erac_cs @mhu.gov.ma",
  "erac_t @seh.gov.ma",
  "eradelmar @menara.ma",
  "erelem @techno.net.ma",
  "eric.lefort@premium.net.ma",
  "ericlefort @premium.net.ma",
  "ericsson @mail.cbi.net.ma",
  "ermabat @wanadoo.net.ma",
  "escanegos @wanadoo.net.ma",
  "esdata @techno.net.ma",
  "esefatih @iam.net.ma",
  "espacemetal @wanadoo.net.ma",
  "espacetravail @menara.ma",
  "espadon @atlasnet.net.ma",
  "esracom @menara.menar.ma",
  "essakhi.n@menara.ma",
  "essounani @cct.ma",
  "etaf @etaf.ma",
  "etametal @wanadoo.net.ma",
  "eteg @iam.net.ma",
  "eteg @menara.net.ma",
  "etis @iam.net.ma",
  "etpec @iam.net.ma",
  "etr @iam.net.ma",
  "etsem @iam.net.ma",
  "etshassoun @iam.net.ma",
  "ettayebi.m@cnia.co.ma",
  "ette @wanadoo.net.ma",
  "ettelmaroc @iam.net.ma",
  "eurabmaroc @menara.ma",
  "eurafricaine @wanadoo.net.ma",
  "eurochimi @menara.ma",
  "eurolocmaroc @menara.ma",
  "europack @marocnet.net.ma",
  "europortas @menara.ma",
  "evolutions - tec@menara.ma",
  "ewimaroc @iam.net.ma",
  "f.amrouni@gsmmaroc.ma",
  "f.benaissa@dislog.ma",
  "f.bourkhiss@alomrane.gov.ma",
  "f.elalaoui@autohall.ma",
  "f.elhadchi@akdital.ma",
  "f.g.a@menara.ma",
  "f.hanafi@tangermed.ma",
  "f.hanafi@tmsa.ma",
  "f.tavaresdepina@menara.ma",
  "f2vrecrutement @casanet.net.ma",
  "fabper @iberostar.ma",
  "fabrilec @wanadoo.net.ma",
  "facemag @facemag.ma",
  "facemag @techno.net.ma",
  "facopmaroc1 @menara.ma",
  "fadiaplastic @menara.ma",
  "fadila @copag.ma",
  "fagor @techno.net.ma",
  "fam @wanadoo.net.ma",
  "famacolor @wanadoo.net.ma",
  "famarco @wanadoo.net.ma",
  "famasser @wanadoo.net.ma",
  "fapeleclustre @wanadoo.net.ma",
  "farmalac @techno.net.ma",
  "fastpack @menara.ma",
  "fatih @poste.ma",
  "fatima.akif@snecma.ma",
  "fatima.boutarbouch@otis.co.ma",
  "fatima.haddour@comarbois.ma",
  "favec @casanet.net.ma",
  "faycal @casanet.net.ma",
  "faysal.chraibi@trc.ma",
  "fbrini @intelcom.co.ma",
  "fcdima @wanadoo.net.ma",
  "fdalil @cpm.co.ma",
  "fenie @iam.net.ma",
  "fer @iam.net.ma",
  "fermoba @iam.net.ma",
  "fermoplast @menara.ma",
  "fertima @fertima.co.ma",
  "fetiane @one.org.ma",
  "fiberopt @iam.net.ma",
  "fil @menara.ma",
  "filas @iam.net.ma",
  "filroc @iam.net.ma",
  "fimme @menara.ma",
  "firm @iam.net.ma",
  "first.casa@wanadoo.net.ma",
  "first.plus@menara.ma",
  "first.telecom@wanadoopro.ma",
  "fitco @iam.net.ma",
  "fitrap @menara.ma",
  "flashgom @iam.net.ma",
  "flmaroc @iam.net.ma",
  "florence.colleau@carrefour-conseil.ma",
  "fluide @iam.net.ma",
  "fm @floquetmonopole.co.ma",
  "fmigc.r@wanadoo.net.ma",
  "fmtm.maroc@menara.ma",
  "fmtmmaroc @menara.ma",
  "fnouchen @diac.co.ma",
  "fogeca @wanadoo.net.ma",
  "fogimac @wanadoo.net.ma",
  "fomec @iam.net.ma",
  "fontec @wanadoo.net.ma",
  "food @wanadoo.net.ma",
  "forafric @menara.ma",
  "forgesdebazas @marocnet.net.ma",
  "formation @gp.ma",
  "fortrade @iam.net.ma",
  "framaco @iam.net.ma",
  "framodir @wanadoopro.ma",
  "france.vidal@devilo.ma",
  "franceicos @iam.ma",
  "franceneon @wanadoo.net.ma",
  "fremmaroc @iam.net.ma",
  "frigchock @iam.net.ma",
  "frigmar @iam.net.ma",
  "frigmar @menara.ma",
  "frmsa @wanadoo.net.ma",
  "froidel @marocnet.net.ma",
  "frumat @techno.net.ma",
  "g.bouchamma@labelvie.ma",
  "g.bureau@iam.net.ma",
  "g.i@casanet.net.ma",
  "g.i@menara.ma",
  "g.ouakrim@cimar.co.ma",
  "g.rousseau@casanet.net.ma",
  "g.tazi@alomrane.gov.ma",
  "g3p @iam.net.ma",
  "gaf @iam.net.ma",
  "galaplast @iam.net.ma",
  "galenica @iam.net.ma",
  "galvacier1 @menara.ma",
  "galvafil @elan.net.ma",
  "gam @casanet.net.ma",
  "gama.industrie@iam.net.ma",
  "garemmaroc @menara.ma",
  "garib @cmpe.ma",
  "garozzo @casanet.net.ma",
  "gaumar @iam.net.ma",
  "gchi.sa@wanadoo.net.ma",
  "gecam @menara.ma",
  "geemag @iam.net.ma",
  "gees @iam.net.ma",
  "geissmann @iam.net.ma",
  "gen.design@menara.ma",
  "genesco @casanet.net.ma",
  "genesco @genesco.ma",
  "genetech @menara.ma",
  "genidis @wanadoo.net.ma",
  "genmulti @iam.net.ma",
  "gepre @iam.net.ma",
  "gerard.condamine@premium.net.ma",
  "germat @iam.net.ma",
  "getradis @iam.net.ma",
  "gfish @iam.net.ma",
  "ghplast @iam.net.ma",
  "gi @menara.ma",
  "gilmarfer @marocnet.net.ma",
  "gindus @iam.net.ma",
  "gitc @wanadoo.net.ma",
  "glass @induvermaroc.ma",
  "glass @protexmaroc.co.ma",
  "global-fisherief@iam.net.ma",
  "global1 @menara.ma",
  "gmcasa @menara.ma",
  "gmce.adt@iam.net.ma",
  "gmdi @iam.net.ma",
  "gmfpa @menara.ma",
  "gmi @iam.net.ma",
  "gmnegoces @menara.ma",
  "gmoperational @menara.ma",
  "gmpb @menara.ma",
  "gmta @wanadoo.net.ma",
  "goldchem @menara.ma",
  "golden.plast@wanadoo.net.ma",
  "golden @menara.ma",
  "gourvenec @iam.net.ma",
  "gpalu @iam.net.ma",
  "gpalus @menara.ma",
  "gpc @iam.net.ma",
  "graderco @graderco.co.ma",
  "granimarbre @wanadoo.net.ma",
  "graphiscript @wanadoo.net.ma",
  "great @iam.net.ma",
  "greening @wanadoo.net.ma",
  "grh1 @autonejma.co.ma",
  "grh @arbor.ma",
  "grh @artco.ma",
  "grh @azzura.com.ma",
  "grh @bituma.ma",
  "griflex @iam.net.ma",
  "grimar @wanadoo.net.ma",
  "grouparc @iam.net.ma",
  "groupedion.mrorcco@menara.ma",
  "groupewelcomaroc @menara.ma",
  "groupewelcomaroc @wanadoo.net.ma",
  "gsmaroc @menara.ma",
  "gtr @gtr.co.ma",
  "guascormaroc @menara.ma",
  "guergachi @cdg.ma",
  "h.abahrouz@ocpgroup.ma",
  "h.abkari@tmsa.ma",
  "h.amor@microdata.ma",
  "h.aouragh@cimr.ma",
  "h.baha@ocpgroup.ma",
  "h.banouar@cmm.ma",
  "h.bekkali@labelvie.ma",
  "h.benmansour@config.ma",
  "h.berka@charcuterie-miami.ma",
  "h.berrada@ocpgroup.ma",
  "h.bouddou@ocpgroup.ma",
  "h.kamil@tmsa.ma",
  "h.moukafih@bmcek.co.ma",
  "h.zioud@promopharm.co.ma",
  "h @wanadoopro.ma",
  "hachad @spontis.ma",
  "hachani.sa@casanet.net.ma",
  "hajjajizakia @orange.ma",
  "hakam @richbond.ma",
  "hamdouni.abdelkrim@adm.co.ma",
  "hamza.sabiri@akwagroup.ma",
  "hanae.bennani@eurocall.ma",
  "hanane.chibel@almabat.ma",
  "hannioui @addoha.ma",
  "hansel.maroc@menara.ma",
  "hasnaa.alaoui@veoliaservices.ma",
  "hasnae.aljamar@awsm.ma",
  "hassan.abahrouz@ocpgroup.ma",
  "hassan.sadali@arist.ma",
  "hassani.idrissi@eqdom.co.ma",
  "haussa @iam.net.ma",
  "haydar @anouaralmostakbal.ma",
  "hbenjelloun @aujourdhui.ma",
  "hbenyachou @marjane.co.ma",
  "hboulkaid @forumin.co.ma",
  "hch @open.net.ma",
  "hcml @wanadoo.net.ma",
  "hcr @techno.net.ma",
  "headoffice @afric-chimie.co.ma",
  "hempel @menara.ma",
  "henimel @iam.net.ma",
  "henkel - maroc@henkel.ma",
  "hfaris @marine-maroc.co.ma",
  "hicham.ghazali@sbs.co.ma",
  "hicham @sumatra.ma",
  "hierro @casanet.net.ma",
  "hivernage.services@iam.net.ma",
  "hjs @iam.net.ma",
  "hlaaziri @acasa.ma",
  "hlagdah @marocleasing.ma",
  "hlahlou @cmh.co.ma",
  "hmaror @acdim.co.ma",
  "holdingonapar @onapar.ma",
  "hopic @wanadoo.net.ma",
  "horani @hps.co.ma",
  "horani @vias.ma",
  "houda.khalid@nexans.co.ma",
  "hp.maroc@hp-maroc.co.ma",
  "hr @avito.ma",
  "hr @dnaengineering.ma",
  "hsbdirection @menara.ma",
  "htnnth @wanadoo.net.ma",
  "huaweiproduits @iam.net.ma",
  "i.abjiou@tangermed.ma",
  "i.amakrane@alomrane.gov.ma",
  "i.bghiel@atlanta.ma",
  "i.minute@menara.ma",
  "i.moukhlisse@holfint.ma",
  "i.moumni@auxel.ma",
  "i.n.c.r@wanadoopro.ma",
  "i.sadki@essaada.ma",
  "i.zouhouredine@4pml.ma",
  "i @baltimar.co.ma",
  "i @iam.net.ma",
  "i @trarem.ma",
  "iac @menara.ma",
  "ibem1 @iam.net.ma",
  "ibemv @menara.ma",
  "ibenjelloun @citelum.ma",
  "ibm.btr@iam.net.ma",
  "ibnmajah @cnesten.org.ma",
  "icaf @icaf.co.ma",
  "icat @iam.net.ma",
  "icoma @menara.ma",
  "ideal @elan.net.ma",
  "ideale.commercial@atlasnet.net.ma",
  "ideale.commerciel@atlasnet.net.ma",
  "ideam @iam.net.ma",
  "idhemmou @cat.co.ma",
  "idp @mail.mis.net.ma",
  "ieci.ma@elan.net.ma",
  "ifarid @marocleasing.ma",
  "ifplast @ifriquiaplasic.co.ma",
  "igest @menara.ma",
  "ihabelec @menara.ma",
  "ihassar @bmcebank.co.ma",
  "iim @wanadoo.ma",
  "ikram.mosleh@orange.ma",
  "im @iam.net.ma",
  "imaghreb @menara.ma",
  "imam.ma@wanadoo.net.ma",
  "imane.bensaid@ehm.ma",
  "imapass @iam.net.ma",
  "imaplast @iam.net.ma",
  "imat @menara.ma",
  "impcrea @iam.net.ma",
  "imprigema @iam.net.ma",
  "imprimatlas @menara.ma",
  "imprimepel @menara.ma",
  "imprimoo @iam.net.ma",
  "inaam @maroc.net.ma",
  "ind @iam.net.ma",
  "indeclair @iam.net.ma",
  "indirrimaroc @menara.ma",
  "indraero @menara.ma",
  "induhos @mail.cbi.net.ma",
  "indumapac @wanadoo.net.ma",
  "indusac @casanet.net.ma",
  "indusalim @casanet.net.ma",
  "induschim @iam.net.ma",
  "industrie @wanadoo.net.ma",
  "industries @maminet.net.ma",
  "ines @ines.ma",
  "info.clever@wanadoo.net.ma",
  "info @agl.ma",
  "info @amgala.ma",
  "info @atlanticclothing.ma",
  "info @bricoma.ma",
  "info @bull.co.ma",
  "info @cmgp.ma",
  "info @creative.ma",
  "info @crifes.ma",
  "info @cst.ma",
  "info @econosol.ma",
  "info @emismaroc.co.ma",
  "info @froidel.ma",
  "info @gim-electronics.ma",
  "info @greenoor.ma",
  "info @iihem.ac.ma",
  "info @ingema.co.ma",
  "info @ingema.ma",
  "info @laayouneinvest.ma",
  "info @lnet.ma",
  "info @macsi.co.ma",
  "info @maghrebnet.net.ma",
  "info @matisol.ma",
  "info @medi1sat.ma",
  "info @mifatelecom.ma",
  "info @musca.ma",
  "info @nedisun.ma",
  "info @nrj.ma",
  "info @pcmarket.co.ma",
  "info @rabatinvest.ma",
  "info @sbs.co.ma",
  "info @scania.co.ma",
  "info @scpc-sapel.ma",
  "info @snr.ma",
  "info @sonasid.ma",
  "info @stroc.ma",
  "info @tbi.ma",
  "info @tractafric.co.ma",
  "info @wanadoo.net.ma",
  "infom @kenitrainvesti.ma",
  "infos @casainvest.ma",
  "infos @fusion.ma",
  "infos @mutronic.ma",
  "infos @passworld.net.ma",
  "infosamir @samir.ma",
  "infosochid @sochid.ma",
  "infotrope @infotrope.net.ma",
  "ingebatt @marocnet.net.ma",
  "ingelec @ingelec.ma",
  "ingenololivier @wanadoo.net.ma",
  "inmeta @iam.net.ma",
  "inovauto @wanadoo.net.ma",
  "inrh @mail.cbi.net.ma",
  "instal @marocnet.net.ma",
  "instel.elec@casanet.net.ma",
  "intechno @casanet.net.ma",
  "inter @iam.net.ma",
  "interact @wanadoo.net.ma",
  "intercaoutchouc @menara.ma",
  "interco @menara.ma",
  "intercomer @wanadoo.net.ma",
  "interdata @ino.net.ma",
  "intergratech @casanet.net.ma",
  "interim @tectra.ma",
  "interkam @iam.net.ma",
  "internos @iam.net.ma",
  "interoutils @iam.net.ma",
  "interrap @iam.net.ma",
  "intersig - karkachi@menara.ma",
  "intraviss @menara.ma",
  "invmaroc @iam.net.ma",
  "iressorts @menara.ma",
  "irizarma @iam.net.ma",
  "isabelle @egida.ma",
  "isao @menara.ma",
  "isc @menara.ma",
  "iskane @casanet.net.ma",
  "islaoui @mafoder.co.ma",
  "isotec.casa@menara.ma",
  "isotec @menara.ma",
  "isotron.maroc@casanet.net.ma",
  "isplast @ifriquiaplastic.co.ma",
  "isuzumaroc @menara.ma",
  "itri - plastic@menara.ma",
  "iturri.maroc@casanet.net.ma",
  "j.hachimi@bimo.co.ma",
  "j.lazrak@labelvie.ma",
  "j.m.c@wanadoo.net.ma",
  "j.mesrour@alomrane.gov.ma",
  "j.mrhardy@tmsa.ma",
  "j.sadiki@attosystems.ma",
  "j.saliane@dardamane.ma",
  "jaafar @cbi.net.ma",
  "jabri.youness@tanger-tetouaninvest.ma",
  "jadiphar @wanadoopro.ma",
  "jado - piel@wanadoo.ma",
  "jahermaroc @menara.ma",
  "jaida.l@menara.ma",
  "jaidi @ciea.ma",
  "jalal.elaroussi@bcm.co.ma",
  "jalal.naji@decathlon.ma",
  "jamal.amrani@jadh.ma",
  "jamal @kitea.ma",
  "jambob @menara.ma",
  "jap @mail.winner.net.ma",
  "jaydoun @cogetel.ma",
  "jbertrand @marocnet.net.ma",
  "jchakir @trarem.ma",
  "jet @casanet.net.ma",
  "jet @dounia.net.ma",
  "jetalu @magrebnet.net.ma",
  "jfk @alpha.net.ma",
  "jlec @jlec.co.ma",
  "jlm @iam.net.ma",
  "jm.patissout@lydec.co.ma",
  "jmendoun @connectcom.net.ma",
  "job @cosimco.ma",
  "job @easycall.ma",
  "job @omnidata.co.ma",
  "jobs @omnidata.ma",
  "jobs @pdt.ma",
  "jobs @sisconsultants.ma",
  "jobway @menara.ma",
  "johan.lancelot@alcatel-lucent.ma",
  "joints @iam.net.ma",
  "jorfplast @wanadoo.net.ma",
  "jpcerio @wanadoo.net.ma",
  "k.benchekroun@cosumar.co.ma",
  "k.bensouda@ocpgroup.ma",
  "k.elalami@bmcek.co.ma",
  "k.jababdi@uniforce.ma",
  "k.jabiri@asmainvest.ma",
  "k.lahlou@menara.ma",
  "kabbadj @cih.co.ma",
  "kadiri @sothema.co.ma",
  "kam1 @iam.net.ma",
  "kamali - talbo@talbo.ma",
  "kamel @amcor.co.ma",
  "kamel @schmalbach.com.ma",
  "kaoutar @mail.cbi.net.ma",
  "karim.zaz@wanadoo.co.ma",
  "karim @annour.ma",
  "karima.elghali@arval.ma",
  "karima.jiraoui@bcc.ma",
  "karkadri - f@menara.ma",
  "karkari @cdgdev.ma",
  "karraz @success.ma",
  "kawtar.bensouda@ocpgroup.ma",
  "kawtar.yassine@inwi.ma",
  "kbenhamida @capinfo.co.ma",
  "kdirect @wanadoo.net.ma",
  "kelhariry @concepts.co.ma",
  "kelmo @casanet.net.ma",
  "kelmo @menara.ma",
  "kemima @menara.ma",
  "keminord @menara.ma",
  "kenza.allouch@capradio.ma",
  "kerama @iam.net.ma",
  "kerbid.co@menara.ma",
  "khadija.bouchrit@awsm.ma",
  "khadija.hamdoune@akzonobel.ma",
  "khairaljanoub @casanet.net.ma",
  "khalid @axomedia.ma",
  "khalil.aouad@creuzet.ma",
  "khiraoui @chaabicourtage.ma",
  "khoungui @caulliez-maroc.co.ma",
  "kidrissi @creditagricole.ma",
  "kimia @iam.net.ma",
  "kitea @kitea.ma",
  "klai @sce.co.ma",
  "kmenaa @meganet.net.ma",
  "kmenaa @menara.ma",
  "koresmaroc @wanadoopro.ma",
  "koumahjoub @munisys.net.ma",
  "koutoubia @iam.ma",
  "koutoubia @iam.net.ma",
  "kraft @kraftfoods.ma",
  "krbenjelloun @distrisoft.co.ma",
  "kroko.maroc@elan.net.ma",
  "ksebraoui @wanadoo.net.ma",
  "kuhn @iam.net.ma",
  "mauro @marocnet.net.ma",
  "mav @mav.ma",
  "mazhar @iam.net.ma",
  "mbantli @trarem.ma",
  "mbd @mail.sis.net.ma",
  "mbs.maroc@menara.ma",
  "mbs.maroc@wanadoo.net.ma",
  "mcco @menara.ma",
  "mchaoui @wanadoo.net.ma",
  "mchoukri @cgi.ma",
  "mci.rh@menara.ma",
  "mcontrol @marocnet.net.ma",
  "mcplv @wanadoopro.ma",
  "mdelec @iam.net.ma",
  "mdm @iam.net.ma",
  "me @iam.net.ma",
  "mecalva @marocnet.net.ma",
  "mecam @iam.net.ma",
  "mecomar @casanet.net.ma",
  "medent @iam.net.ma",
  "mediaco @techno.net.ma",
  "mediacom @iam.net.ma",
  "medicable @menara.ma",
  "medidis @wanadoo.net.ma",
  "meding @wanadoo.net.ma",
  "mega.hissoto@wanadoo.net.ma",
  "megec @menara.ma",
  "mehdi.hazzaz@cdm.ma",
  "mekkoudi @menara.ma",
  "meknesinvest @menara.ma",
  "melb @laurentbouillet.ma",
  "melbakni @acima.co.ma",
  "melhajji @comptoirservice.ma",
  "melton.maghreb@menara.ma",
  "menara.prefa@iam.net.ma",
  "menaracolor @iam.net.ma",
  "mercure.indust@casanet.net.ma",
  "mermoux @upline.co.ma",
  "meryem - t@anrt.net.ma",
  "meryem.guennouni@acred.ma",
  "mesa @iam.net.ma",
  "mest @mest.co.ma",
  "mesure @wanadoo.net.ma",
  "metacma @iam.net.ma",
  "metalesextruidos @menara.ma",
  "metallifni @wanadoopro.ma",
  "methodealunion @iam.net.ma",
  "metonor @iam.net.ma",
  "meziani @creditagricole.ma",
  "mge.ups.maroc@elan.net.ma",
  "mice @elan.net.ma",
  "michoc @wanadoo.net.ma",
  "microspire.maroc@menara.ma",
  "micser @menara.ma",
  "midav @midav.ma",
  "miden @miden.co.ma",
  "mifa @open.net.ma",
  "mika @casanet.net.ma",
  "mikafric @casanet.net.ma",
  "mikea @iam.net.ma",
  "mimmobilier @menara.ma",
  "minco @minco.ma",
  "minel @marocnet.net.ma",
  "minotsahara @menara.ma",
  "mis @techno.net.ma",
  "misen @photovoltaique.ma",
  "mjamai @orsys.co.ma",
  "mjnainy @oulmes.ma",
  "mkharti @cmi.co.ma",
  "mlpcrehu01 @clubmed.ma",
  "mmarketing @autonejma.co.ma",
  "mmep @wanadoopro.ma",
  "mmmi @iam.net.ma",
  "mnider @cnca.co.ma",
  "mnord @iam.net.ma",
  "mo @techno.net.ma",
  "mobidir @mobilia.ma",
  "mobikit @mobilia.ma",
  "moder @iam.net.ma",
  "modfak @iam.net.ma",
  "moga.elec@iam.net.ma",
  "mogesse @techno.net.ma",
  "mohamed.bajjou@marsamaroc.co.ma",
  "mohamed.malha@fujitsu-siemens.co.ma",
  "mohamed.mtiri@acred.ma",
  "mohammed.akkad@orange.ma",
  "mohammed.malha@wincor-nixdorf.co.ma",
  "mohdavnor @menara.ma",
  "mokala @wanadoo.net.ma",
  "mondel @casanet.net.ma",
  "mondial.motors@casanet.net.ma",
  "moplasinternational @menara.ma",
  "motex @motex.co.ma",
  "motii @menara.ma",
  "motorsa @iam.net.ma",
  "mouhajir @lesieur-cristal.co.ma",
  "moulins1 @menara.ma",
  "moumchih @novaxys.ma",
  "moumni @crimarrakech.ma",
  "mounir @atlantic.co.ma",
  "mounir @mitel.ma",
  "mourad @allogroupe.ma",
  "moursli @univers.co.ma",
  "mpe @mpe.ma",
  "mpi @menara.ma",
  "mpia @menara.ma",
  "mpsff @open.net.ma",
  "mr - clean@iam.net.ma",
  "mrica @iam.net.ma",
  "mrica @menara.ma",
  "mrs @wanadoo.net.ma",
  "mrtng @iam.net.ma",
  "ms @iam.net.ma",
  "msa @menara.ma",
  "mscomposites @menara.ma",
  "msd @iam.net.ma",
  "msit @atlasnet.net.ma",
  "msoual @s2m.net.ma",
  "msoubhi @scbg.ma",
  "mt @maroctransfo.ma",
  "mtcom @iam.net.ma",
  "mtf @marocnet.net.ma",
  "mtsouli @tria.ma",
  "mulplast @iam.net.ma",
  "multi - neon@marocnet.net.ma",
  "multicolles @menara.ma",
  "multifibres @iam.net.ma",
  "mustad @iam.net.ma",
  "mustapha.bouhami@arabbank.ma",
  "mustapha.zoufoudi@cniasaada.ma",
  "myriam.elkarzazi@premium.net.ma",
  "mzerhouni @nabc.ma",
  "n.daoudi@wafaimmobilier.co.ma",
  "n.fassifihri@ona.co.ma",
  "n.joundy@onp.ma",
  "n.slimani@labelvie.ma",
  "n5c @iam.net.ma",
  "n @athena.online.co.ma",
  "nabil.elkhalidy@axa.ma",
  "nabiljaidi @casanet.net.ma",
  "naciri @cmh.co.ma",
  "nadhis @menara.ma",
  "nadia.belouane@manpower-maroc.ma",
  "nadia @africode.ma",
  "nadia @lecomptoir.ma",
  "nadlousse @fertima.co.ma",
  "naitaiss @marocexport.ma",
  "najat.tadlaoui@cimr.ma",
  "naji @ctm.ma",
  "najiaz @iam.net.ma",
  "namet @iam.net.ma",
  "naoual.ouaffak@marsamaroc.co.ma",
  "napco @iam.net.ma",
  "nat @menara.ma",
  "nath.abdas@iam.net.ma",
  "natinov @menara.ma",
  "natmanu @menara.ma",
  "nb @casanet.net.ma",
  "nbm @iam.net.ma",
  "nbr @nbr.ma",
  "negochim @menara.ma",
  "nera @iam.net.ma",
  "networksarl @menara.ma",
  "nili @somanex.ma",
  "nitam @menara.ma",
  "nitra @wanadoo.net.ma",
  "niwel @menara.ma",
  "nkhalil @marjane.co.ma",
  "nmalek @alliances.co.ma",
  "nmarc @menara.ma",
  "nobelbus @menara.ma",
  "nofine @menara.ma",
  "nombret @menara.ma",
  "norigem @menara.ma",
  "norton.maroc@casanet.net.ma",
  "notelec @iam.net.ma",
  "notemac @menara.ma",
  "noureddine.mesbahi@coficab.ma",
  "nouvelle - somatam@casanet.net.ma",
  "novacerame @iam.net.ma",
  "novaprim @maghrebnet.net.ma",
  "novovet @novovet.ma",
  "nrfmaroc @atlasnet.net.ma",
  "nrj @wanadoo.ma",
  "nsami @iam.net.ma",
  "nthechim @iam.net.ma",
  "nzoubidy @gbm.ma",
  "o.fares@tv2m.co.ma",
  "o.outaleb@casanet.net.ma",
  "o.oxyfer@iam.net.ma",
  "o.tazi@sothema.ma",
  "oabdelkarim @cccl.ma",
  "ocbm @menara.ma",
  "ocm @marocnet.net.ma",
  "ocp.drh@ocpgroup.ma",
  "odep.hoceima@menara.ma",
  "odimatic @iam.net.ma",
  "ogcsarl @iam.net.ma",
  "ogden @marocnet.net.ma",
  "oge @iam.net.ma",
  "ogermaroc @iam.net.ma",
  "ogin @wanadoo.net.ma",
  "okad @menara.ma",
  "oksa @oksamaroc.co.ma",
  "omar @elan.net.ma",
  "omarham @fagor.ma",
  "omatec @casanet.net.ma",
  "omce @wanadoo.net.ma",
  "omelec - dir@casanet.net.ma",
  "omelec - techn@casanet.net.ma",
  "ometougui @marocleasing.ma",
  "omnep @menara.ma",
  "omnia.intaj@iam.net.ma",
  "omnicaoutchouc @menara.ma",
  "omtec.batiment@menara.ma",
  "omtec @iam.net.ma",
  "ona_recrutement @ona.co.ma",
  "onarepdg @acdim.net.ma",
  "onda @onda.ma",
  "onepbo @onep.ma",
  "onerep @marocnet.net.ma",
  "onp @onp.co.ma",
  "optima @iam.net.ma",
  "optimachimie @techno.net.ma",
  "orapplis @casanet.net.ma",
  "orbit @wanadoo.net.ma",
  "orca @orca.ma",
  "ori - mec@iam.net.ma",
  "oriental.medica@espacenet.net.ma",
  "orkmor @iam.net.ma",
  "orkref @menara.ma",
  "orthomed @menara.ma",
  "ouajdi @pharma5.ma",
  "ouderni @mfc.ma",
  "ouizzane_ismail @chk.ma",
  "oukacha @one.org.ma",
  "ounes - b@menara.ma",
  "ourelec1 @menara.ma",
  "ourvenec @iam.net.ma",
  "oussamasa @atlasnet.net.ma",
  "outicom @marocnet.net.ma",
  "outicom @wanadoopro.ma",
  "outillageservice @menara.ma",
  "rosachim @casanet.net.ma",
  "rosca @wanadoo.net.ma",
  "roudghiri @mail.fedaso.co.ma",
  "rouger @wanadoo.net.ma",
  "rpd @menara.ma",
  "rpdcom @menara.ma",
  "rrafik @pema.ma",
  "rsifi @abercrombiekent.ma",
  "rtelinhos @sunviauto.ma",
  "rtirans @iam.net.ma",
  "ruberoid @iam.net.ma",
  "rvd @wanadoo.net.ma",
  "s - ennajbi@sodexho.co.ma",
  "s.agourrame@agsconseil.ma",
  "s.arraf@albatroslogistic.ma",
  "s.b.s@iam.net.ma",
  "s.bendoumah@labelvie.ma",
  "s.bounsir@akdital.ma",
  "s.bourzag@coparchim.ma",
  "s.bourziq@citruma.ma",
  "s.chems@iam.net.ma",
  "s.ghandi@wanadoo.net.ma",
  "s.labrahmi@stcr.ma",
  "s.limouni@smac.ma",
  "s.loudghiri@tmsa.ma",
  "s.m.colles@atlasnet.net.ma",
  "s.mann@iam.net.ma",
  "s.menouni@casanet.ma",
  "s.n.h@menara.ma",
  "s.omp@iam.net.ma",
  "s.sifeddine@labelvie.ma",
  "s.tahiri@askadvisory.ma",
  "s @atlasnet.net.ma",
  "s @iam.net.ma",
  "s @menara.ma",
  "s @wanadoo.net.ma",
  "sa @casanet.ma",
  "sa @wanadoopro.ma",
  "saa @iam.net.ma",
  "saad @atlastelecom.ma",
  "sacredmaroc @wanadoo.net.ma",
  "sadake @iam.net.ma",
  "sadco @iam.net.ma",
  "sadettemara @iam.net.ma",
  "sadifa @iam.net.ma",
  "sadifa @menara.ma",
  "sadvel @plvplus.net.ma",
  "saem @wanadoo.net.ma",
  "safap @wanadoo.net.ma",
  "safilum @techno.net.ma",
  "safripac @menara.ma",
  "saharaclim @menara.ma",
  "saheg @iam.net.ma",
  "sahiaoui @casanet.net.ma",
  "saida @menara.ma",
  "saida @solarexport.ma",
  "saimaco @iam.net.ma",
  "saimane @casanet.net.ma",
  "sainani @beuginmaroc.ma",
  "saissc7r7ales @iam.net.ma",
  "salamgaz @iam.net.ma",
  "sales @menara.ma",
  "salhi.man@sefamar.ma",
  "salim @comanav.co.ma",
  "salim @wanadoo.net.ma",
  "salimaho @iam.net.ma",
  "salouigeps @menara.ma",
  "sam @iam.net.ma",
  "samab.mar@elan.net.ma",
  "samareco @menara.net.ma",
  "samfor @casanet.net.ma",
  "samifimaroc @wanadoo.net.ma",
  "samira.sbai@lazrak.ma",
  "samireg @menara.ma",
  "sanaa.belmrah@cetelem.co.ma",
  "sanaam @ingelec.ma",
  "sanichaud @iam.net.ma",
  "sanifer @atlasnet.net.ma",
  "sanirama @iam.net.ma",
  "sanitube @iam.net.ma",
  "sap @menara.ma",
  "saralum @iam.net.ma",
  "sareleb @wanadoo.net.ma",
  "sarsaramks @iam.net.ma",
  "sasaranks @menara.ma",
  "sba @cimat.ma",
  "sbata @artemis.co.ma",
  "sbenzidia @casablanca.ma",
  "sbgs @agadirnet.net.ma",
  "sbougattaya @s2m.net.ma",
  "sbpr @menara.ma",
  "sbuzinkay @deloitte.co.ma",
  "sc @iam.net.ma",
  "scaffolding @wanadoo.net.ma",
  "scam @marocnet.net.ma",
  "scama @scama.ma",
  "scandi @iam.net.ma",
  "scandi @menara.ma",
  "scapir @iam.net.ma",
  "sceacier @iam.net.ma",
  "scepers.rrimaroc@menara.ma",
  "scet @scet.ma",
  "schielemaroc @menara.ma",
  "schielemaroc @wanadoo.net.ma",
  "schlemmer.maroc@iam.net.ma",
  "schneberger @menara.ma",
  "schneider @schneider.ma",
  "scrim @iam.net.ma",
  "sdaeboukitab @menara.ma",
  "sdbp @iam.net.ma",
  "sdbp @menara.ma",
  "sdg @onmt.org.ma",
  "sdim @iam.net.ma",
  "sdl @marocnet.net.ma",
  "sebbar.fouad@makro.co.ma",
  "secdg @oncf.org.ma",
  "secincendie @menara.ma",
  "secretariat @sce.co.ma",
  "securitel @iam.net.ma",
  "sedaica @iam.net.ma",
  "sedavmar @iam.net.ma",
  "seddik @menara.ma",
  "sedric @menara.ma",
  "sefcam @menara.ma",
  "sefiani.sa@menara.ma",
  "segh @iam.net.ma",
  "segmo1 @menara.ma",
  "segmo @iam.net.ma",
  "segoh @menara.ma",
  "segrafire @sis.net.ma",
  "sehi @elan.net.ma",
  "selfa @selfa.ma",
  "sem @wanadoo.net.ma",
  "semema @iam.net.ma",
  "semlali @afriquia.co.ma",
  "sems @menara.ma",
  "senad @wanadoo.net.ma",
  "senomar @iam.net.ma",
  "seprob @iam.net.ma",
  "seprosi @menara.ma",
  "serea @iam.net.ma",
  "sergef @inter.net.ma",
  "sergef @menara.ma",
  "sersud @menara.ma",
  "serviges @menara.ma",
  "servouti @casanet.net.ma",
  "setima @iam.net.ma",
  "sevam @iam.net.ma",
  "sevena @iam.net.ma",
  "sevena @menara.ma",
  "sevolta @iam.net.ma",
  "sfcm @iam.net.ma",
  "sfrm3 @menara.ma",
  "sfrm @wanadoopro.ma",
  "sga @iam.net.ma",
  "sga @iam.pro.ma",
  "sgee @menara.ma",
  "sgms @casanet.net.ma",
  "sgsmaroc @iam.net.ma",
  "sgtbo @wanadoo.net.ma",
  "sgtm.dg@iam.net.ma",
  "sherpagad @menara.ma",
  "show @mail.cbi.net.ma",
  "si3 @aim.net.ma",
  "siatra @casanet.net.ma",
  "sibele @iam.net.ma",
  "sibrelec @menara.ma",
  "sicda @casanet.ma",
  "sicda @menara.ma",
  "sicofer @wanadoo.net.ma",
  "sicopa @menara.ma",
  "sicopa @wanadoo.net.ma",
  "sidelec @wanadoo.net.ma",
  "siden @maghrebnet.net.ma",
  "sidiali @oulmes.ma",
  "sie1 @menara.ma",
  "siege @cmt.ma",
  "sielorient @iam.net.ma",
  "siemens @siemens.co.ma",
  "sif @iam.net.ma",
  "sifap @menara.ma",
  "sifapcasa @iam.net.ma",
  "sifapcasa @menara.ma",
  "sigma @sigmaship.ma",
  "sigmatec @iam.net.ma",
  "sigmatel @sigmatel.net.ma",
  "siham.benkhalifa@chaabilld.ma",
  "sikamaroc @casanet.net.ma",
  "sikamaroc @wanadoopro.ma",
  "silocasa @iam.net.ma",
  "silverpeinture @menara.ma",
  "simec @simec.ma",
  "simmons @casanet.net.ma",
  "simmons @simmons.ma",
  "simon.int@casanet.net.ma",
  "simotem @iam.net.ma",
  "sinointer @menara.ma",
  "sinomar @iam.net.ma",
  "sinomar @menara.ma",
  "sinped @iam.net.ma",
  "siof @menara.ma",
  "sipromed @casanet.net.ma",
  "sirmel @wanadoo.net.ma",
  "sistina @menara.ma",
  "sitelec @menara.ma",
  "sjamaa @omnidata.ma",
  "sklop - caoutchouc@marocnet.net.ma",
  "sl @menara.ma",
  "slassi @netcom.co.ma",
  "smaap @iam.net.ma",
  "smaco @open.net.ma",
  "smactp @casanet.net.ma",
  "smadia @connectcom.net.ma",
  "smadire @elan.net.ma",
  "smadire @menara.ma",
  "smaprec @iam.net.ma",
  "smar @casanet.net.ma",
  "smartnet1 @iam.net.ma",
  "smatra @iam.net.ma",
  "smca @iam.net.ma",
  "smca @menara.ma",
  "smcim @menara.ma",
  "smec @menara.ma",
  "smeclim @iam.net.ma",
  "smein @menara.ma",
  "smem @menara.ma",
  "smeor @iam.net.ma",
  "smet @smet.ma",
  "smeteg @menara.ma",
  "smic @wanadoo.net.ma",
  "smifam @wanadoo.net.ma",
  "smjcarb @wanadoopro.ma",
  "smohib @s2m.ma",
  "smp @techno.net.ma",
  "smri @elan.net.ma",
  "snabt @menara.ma",
  "snal @iam.ma",
  "snce @iam.net.ma",
  "snco @iam.net.ma",
  "snecma.morocco@snecma.ma",
  "sned @sned.gov.ma",
  "sneth @iam.net.ma",
  "snmm @mail.cbi.net.ma",
  "snro @iam.net.ma",
  "snumm @wanadoo.net.ma",
  "snv @iam.net.ma",
  "soberma @soberma.ma",
  "sobovat @menara.ma",
  "socal @marocnet.net.ma",
  "socarlage @iam.net.ma",
  "sochid @sochid.ma",
  "sochpev @sis.net.ma",
  "socimar @marocnet.net.ma",
  "socipri @iam.net.ma",
  "sococharbo @casanet.net.ma",
  "socodra @iam.net.ma",
  "socofeb @menara.ma",
  "socoga @menara.ma",
  "socomadis @menara.ma",
  "socoreg @menara.ma",
  "socotan @wanadoo.net.ma",
  "socotec.rab@menara.ma",
  "socotecfes @menara.ma",
  "socotecm @marocnet.net.ma",
  "socotecmrk @menara.ma",
  "socotectan @menara.ma",
  "sodap @mabar.co.ma",
  "sodeprim @elan.net.ma",
  "sodevic @iam.net.ma",
  "sodiflex @wanadoo.net.ma",
  "sodipro @iam.net.ma",
  "sodirep @wanadoo.net.ma",
  "sodisma @iam.net.ma",
  "soebard @iam.net.ma",
  "soelso @menara.ma",
  "sofa @sofa.co.ma",
  "sofacuis @iam.net.ma",
  "sofacuis @menara.ma",
  "sofafer @iam.net.ma",
  "sofem @wanadoopro.ma",
  "sofidet @iam.net.ma",
  "sofimed @iam.net.ma",
  "sofinas @iam.net.ma",
  "sofirec @iam.net.ma",
  "sofisoft @iam.net.ma",
  "sofometal @iam.net.ma",
  "sofradis @atlasnet.net.ma",
  "soframar @soframar.co.ma",
  "soframar @wanadoo.net.ma",
  "sofrenor @iam.net.ma",
  "sogec @menara.ma",
  "sogedir @iam.net.ma",
  "sogefab @menara.ma",
  "sogeres.ma@casanet.net.ma",
  "sogeric @iam.net.ma",
  "soget @iam.net.ma",
  "sogetrama @menara.ma",
  "sogetub @casanet.net.ma",
  "sohime @iam.net.ma",
  "solind @casanet.net.ma",
  "solsif @iam.net.ma",
  "soluba @menara.ma",
  "soma @iam.net.ma",
  "soma @somaprol.ma",
  "somaca - optimumbpi@wanadoopro.ma",
  "somachame @wanadoo.net.ma",
  "somacharme @wanadoo.net.ma",
  "somacoc @wanadoo.net.ma",
  "somacor @wanadoo.net.ma",
  "somadiag @wanadoo.ma",
  "somadiaz @wanadoo.net.ma",
  "somadiaz @wanadoopro.ma",
  "somafero @iam.net.ma",
  "somafob @wanadoo.net.ma",
  "somagal @wanadoopro.ma",
  "somagec @somagec.ma",
  "somalar @casanet.net.ma",
  "somana @iam.net.ma",
  "somara @wanadoopro.ma",
  "somarac @iam.net.ma",
  "somaver @menara.ma",
  "somea @iam.net.ma",
  "somed @somed.ma",
  "somedgroup @iam.net.ma",
  "somint @iam.net.ma",
  "somma @somma.ma",
  "somon @menara.ma",
  "somrap - sarl@menara.ma",
  "sonaba @iam.net.ma",
  "sonacar @sonacar.ma",
  "sonacob @iam.net.ma",
  "sonasid @nadornet.net.ma",
  "soner @casanet.net.ma",
  "sonexi @menara.ma",
  "soniama @iam.net.ma",
  "sonorac @wanadoopro.ma",
  "soralec @menara.ma",
  "sorasi @menara.ma",
  "soraya.tahri@tgcc.ma",
  "soremar @soremar.co.ma",
  "sorepri @menara.ma",
  "sorfic @iam.net.ma",
  "sorinor @iam.net.ma",
  "sosipo @menara.ma",
  "sosndd @wanadoo.net.ma",
  "soteca @iam.net.ma",
  "sotemag @menara.ma",
  "sotradema @iam.net.ma",
  "sotramap @iam.net.ma",
  "sotrameg @iam.net.ma",
  "sotravo.i@menara.ma",
  "soudmetal @iam.net.ma",
  "soukret @iam.net.ma",
  "soumia.widadi@axa.ma",
  "sovirec @menara.ma",
  "sowlamine @bestpro.co.ma",
  "spc @iam.net.ma",
  "spidernet @casablanca-technopark.ma",
  "spinelec06 @menara.ma",
  "spm @iam.net.ma",
  "sppp @open.net.ma",
  "spts @wanadoopro.ma",
  "srkaibi @omnidata.co.ma",
  "ssonic @menara.ma",
  "st @iam.net.ma",
  "st @menara.ma",
  "sta @iam.net.ma",
  "stages @smmrgv.ma",
  "starlub @techno.net.ma",
  "ste.sohapa@iam.net.ma",
  "steagregats @menara.ma",
  "stecica @iam.net.ma",
  "stem @casanet.net.ma",
  "steph @macsi.co.ma",
  "steptd.kfm@menara.ma",
  "sterelec @iam.net.ma",
  "sterimax @iam.net.ma",
  "stezahid @iam.net.ma",
  "stezahid @menara.ma",
  "stherm @maghrebnet.net.ma",
  "stillemans @iam.net.ma",
  "stm @tanja.net.ma",
  "stroc @iam.net.ma",
  "sudelec @iam.net.ma",
  "sudgalva @menara.ma",
  "sunabel @iam.net.ma",
  "supauto @iam.net.ma",
  "super.lait@iam.net.ma",
  "suport.ebds@cnss.ma",
  "svn @iam.net.ma",
  "syntone @iam.net.ma",
  "t.detroit@iam.net.ma",
  "t.sigma@atlasnet.net.ma",
  "t.sigma@iam.net.ma",
  "t @iam.net.ma",
  "t @menara.ma",
  "tagmat @iam.net.ma",
  "taieb.alaoui@sbs.co.ma",
  "taif @agrinmaroc.ma",
  "a.bourakkadi@zakourafondation.org",
  "contact@iresen.org",
  "fitzgerald@clcmorocco.org",
  "l.rabbaj@anapec.org",
  "larbibois@menara.org",
  "ollearis-maghreb@ollearis.org",
  "rh@efemaroc.org",
  "roster@acdivoca.org",
  "elmostafa.khaledi@yazaki-europe.zurich",
  "bmota@aubay.pt",
  "noresec@esec.lda.pt",
  "jonas.lindh@memo.ericsson.se",
  "hafida.tallal@ma.schneider-electric.somadir",
  "climabel@fr.st",
  "abdelhamid.elmalki@queria.tech",
  "yo@usem.tech",
  "mohamed.benmezouara@bim.com.tr",
  "natashascarth@spectrumit.co.uk",
  "africa.applications@shell.co.za",
  "mohamed.benouarrek@pharma.novartis.ona",
  "mimoun.boujemaaoui@gasnaturalsdg.metro",
  "sanny.sefrioui@marocaviation.eads.matel",
  "fatimazahra_abbadi.idrissi@meditel.maroc",
  "akseibet@rja.com.jo",
  "abdellah.benadi@denso-ts.it",
  "ipsamar@ipsaweb.it",
  "m.menegari@sews-cabind.it",
  "n.bouabid@sews-cabind.it",
  "paolocs63@yahoo.it",
  "amine@journify.io",
  "info@x-hub.io",
  "mohamed@digitribe.io",
  "recrutement@beyn.io",
  "mouina.daoui@inabensamaroc.abengoa.intelcia",
  "recruitment.morocco@jtekt.eu",
  "zineb.benhima@akka.eu",
  "recrutement@qair.energy",
  "d.s.f@mail.dk",
  "info@tec-inspection.de",
  "said.ameziane@bayer-ag.de",
  "sofia.ifrah.si@bayer-ag.de",
  "tania.abreu-ext@conti.de",
  "ghita@colibristudio.co",
  "bouchra.moutaoukil@eur.crowncork.club",
  "khadija.huebra@sonate.cloud",
  "lbourdon@heyme.care",
  "support-it@heyme.care",
  "egoyeneche@astek-canada.ca",
  "infos@arcanes.biz",
  "m2t@m2t.biz",
  "morocco.hr@sabca.be",
  "widemar@widem.be",
  "talent@elavi.agency",
  "adil@xpertise.africa",
  "widmarck@xpertize.africa",
  "yazid@xpertise.africa",
  "shamery@emaar.ae",
  "amina@tcrew.be"
];


module.exports = emails;